name: captain
description: Roshan League app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  firebase_core:
  firebase_auth:
  firebase_storage:
  shared_preferences:
  http: 
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  cloud_firestore:
  flutter_cache_manager: ^3.3.1 
  intl_phone_field: ^3.2.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.0
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  awesome_dialog: ^3.1.0
  animated_text_kit: ^4.2.2
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_markdown: ^0.6.18
  flutter_polls: ^0.1.5
  youtube_player_flutter: ^8.1.2
  sign_in_button: ^3.2.0
  url_launcher: ^6.2.2
  lottie: ^3.0.0
dev_dependencies:
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lint: ^2.1.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/luncher_icon.png"
  adaptive_icon_background: "#070C19"
  adaptive_icon_foreground: "assets/Image/luncher_icon.png"

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/light_app_icon.png
  branding: assets/image/light_app_icon.png
  color_dark: "#070C19"
  image_dark: assets/image/dark_app_icons.png
  branding_dark: assets/image/dark_app_icons.png

  android_12:
    image: assets/image/light_app_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/image/dark_app_icons.png
    icon_background_color_dark: "#070C19"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Image/
    - assets/Privacy & Policy/privacy_policy.md

  fonts:
    - family: Tajawal-Black
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
    - family: Tajawal-Bold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    - family: Tajawal-ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
    - family: Tajawal-Light
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf