name: sportsbet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_ui_auth: 
  firebase_analytics:
  getx_screen: ^1.0.0
  shared_preferences: 
  http: 
  smart_auth: ^1.1.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  json_theme: ^6.3.0
  cloud_firestore:
  line_awesome_flutter: ^2.0.0
  flutter_cache_manager: ^3.3.1 
  firebase_database: ^10.2.5
  curved_labeled_navigation_bar: ^2.0.2
  animated_notch_bottom_bar: ^1.0.0
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  calendar_timeline: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  pinput: ^3.0.1
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.0
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  google_nav_bar: ^5.0.6
  floating_bottom_navigation_bar: ^1.5.2
  syncfusion_flutter_charts: ^23.1.38
  flutter_fortune_wheel: ^1.3.0
  anim_search_bar: ^2.0.3
  awesome_dialog: ^3.1.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.14
  flutter_phone_direct_caller: ^2.1.1
  flutter_email_sender: ^6.0.2
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1584889.png"
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/1584889.png"
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Image/
    - assets/Image/loading.png
    - assets/Image/no_internet.png

  fonts:
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBM/IBMPlexSans-Bold.ttf
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBM/IBMPlexSans-Medium.ttf
    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBM/IBMPlexSans-Regular.ttf
    - family: Tajawal-Black
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
    - family: Tajawal-Bold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    - family: Tajawal-ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
    - family: Tajawal-Light
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf